"use client";

import gartenzwerg_schubkarren from "@/assets/images/Upgrades/Gartenzwerg_Schubkarren.png";
import gartenzwerg_heckenschere from "@/assets/images/Upgrades/Gartenzwerg_Heckenschere.png";
import gartenzwerg_handwerker from "@/assets/images/Upgrades/Gartenzwerg_Handwerker.png";
import gartenzwerg_mine from "@/assets/images/Upgrades/Gartenzwerg_Mine.png";
import gartenzwerg_rubin from "@/assets/images/Upgrades/Gartenzwerg_Rubin.png";
import gartenzwerg_saphir from "@/assets/images/Upgrades/Gartenzwerg_Saphir.png";
import gartenzwerg_elefant from "@/assets/images/Upgrades/Gartenzwerg_Elefant.png";
import gartenzwerg_kamel from "@/assets/images/Upgrades/Gartenzwerg_Kamel.png";
import gartenzwerg_schneckenreiter from "@/assets/images/Upgrades/Gartenzwerg_Schneckenreiter.png";
import gartenzwerg_lokomotive from "@/assets/images/Upgrades/Gartenzwerg_Lokomotive.png";
import gartenzwerg_scherbenmaschine from "@/assets/images/Upgrades/Gartenzwerg_Scherbenmaschine.png";
import gartenzwerg_ballon from "@/assets/images/Upgrades/Gartenzwerg_Ballon.png";
import gartenzwerg_mond from "@/assets/images/Upgrades/Gartenzwerg_Mond.png";
import gartenzwerg_geist from "@/assets/images/Upgrades/Gartenzwerg_Geist.png";
import gartenzwerg_eis from "@/assets/images/Upgrades/Gartenzwerg_Eis.png";
import gartenzwerg_riese from "@/assets/images/Upgrades/Gartenzwerg_Riese.png";
import gartenzwerg_surfer from "@/assets/images/Upgrades/Gartenzwerg_Surfer.png";
import gartenzwerg_bergsteiger from "@/assets/images/Upgrades/Gartenzwerg_Bergsteiger.png";
import gartenzwerg_pirat from "@/assets/images/Upgrades/Gartenzwerg_Pirat.png";
import gartenzwerg_bademeister from "@/assets/images/Upgrades/Gartenzwerg_Bademeister.png";
import gartenzwerg_soldat from "@/assets/images/Upgrades/Gartenzwerg_Soldat.png";
import { UPGRADE_TYPES } from "./constants";

const upgradeList = [
  {
    image: gartenzwerg_schubkarren,
    costs: 25,
    anzahl: 1,
    possession: 0,
    title: "Schubkarren",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+1 Scherbe pro Sekunde",
    buyed: false,
    id: 1,
  },
  {
    image: gartenzwerg_heckenschere,
    costs: 75,
    anzahl: 2,
    possession: 0,
    title: "Heckenschere",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+2 Scherben pro Klick",
    buyed: false,
    id: 2,
  },
  {
    image: gartenzwerg_handwerker,
    costs: 150,
    anzahl: 3,
    possession: 0,
    title: "Handwerker",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+3 Scherben pro Sekunde",
    buyed: false,
    id: 3,
  },
  {
    image: gartenzwerg_mine,
    costs: 400,
    anzahl: 8,
    possession: 0,
    title: "Mine",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+8 Scherben pro Klick",
    buyed: false,
    id: 4,
  },
  {
    image: gartenzwerg_rubin,
    costs: 900,
    anzahl: 18,
    possession: 0,
    title: "Rubin",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+18 Scherben pro Sekunde",
    buyed: false,
    id: 5,
  },
  {
    image: gartenzwerg_saphir,
    costs: 1800,
    anzahl: 36,
    possession: 0,
    title: "Saphir",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+36 Scherben pro Klick",
    buyed: false,
    id: 6,
  },
  {
    image: gartenzwerg_elefant,
    costs: 4500,
    anzahl: 90,
    possession: 0,
    title: "Elefant",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+90 Scherben pro Sekunde",
    buyed: false,
    id: 7,
  },
  {
    image: gartenzwerg_kamel,
    costs: 9000,
    anzahl: 180,
    possession: 0,
    title: "Kamel",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+180 Scherben pro Klick",
    buyed: false,
    id: 8,
  },
  {
    image: gartenzwerg_schneckenreiter,
    costs: 15000,
    anzahl: 300,
    possession: 0,
    title: "Schneckenreiter",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+300 Scherben pro Sekunde",
    buyed: false,
    id: 9,
  },
  {
    image: gartenzwerg_lokomotive,
    costs: 27000,
    anzahl: 540,
    possession: 0,
    title: "Lokomotive",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+540 Scherben pro Klick",
    buyed: false,
    id: 10,
  },
  {
    image: gartenzwerg_scherbenmaschine,
    costs: 40000,
    anzahl: 800,
    possession: 0,
    title: "ScherbenMaschine",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+800 Scherben pro Sekunde",
    buyed: false,
    id: 11,
  },
  {
    image: gartenzwerg_ballon,
    costs: 85000,
    anzahl: 1700,
    possession: 0,
    title: "Ballon",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+1700 Scherben pro Klick",
    buyed: false,
    id: 12,
  },
  {
    image: gartenzwerg_mond,
    costs: 175000,
    anzahl: 3500,
    possession: 0,
    title: "Mond",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+3500 Scherben pro Sekunde",
    buyed: false,
    id: 13,
  },
  {
    image: gartenzwerg_geist,
    costs: 350000,
    anzahl: 7000,
    possession: 0,
    title: "Geist",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+7000 Scherben pro Klick",
    buyed: false,
    id: 14,
  },
  {
    image: gartenzwerg_eis,
    costs: 700000,
    anzahl: 14000,
    possession: 0,
    title: "Eis",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+14000 Scherben pro Sekunde",
    buyed: false,
    id: 15,
  },
  {
    image: gartenzwerg_riese,
    costs: 1500000,
    anzahl: 30000,
    possession: 0,
    title: "Riese",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+30000 Scherben pro Klick",
    buyed: false,
    id: 16,
  },
  {
    image: gartenzwerg_bergsteiger,
    costs: 3000000,
    anzahl: 60000,
    possession: 0,
    title: "Bergsteiger",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+60000 Scherben pro Sekunde",
    buyed: false,
    id: 17,
  },
  {
    image: gartenzwerg_pirat,
    costs: 6500000,
    anzahl: 130000,
    possession: 0,
    title: "Pirat",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+130000 Scherben pro Klick",
    buyed: false,
    id: 18,
  },
  {
    image: gartenzwerg_surfer,
    costs: 14000000,
    anzahl: 280000,
    possession: 0,
    title: "Surfer",
    type: UPGRADE_TYPES.INTERVAL,
    tooltipDescription: "+280000 Scherben pro Sekunde",
    buyed: false,
    id: 19,
  },
  {
    image: gartenzwerg_bademeister,
    costs: 30000000,
    anzahl: 600000,
    possession: 0,
    title: "Bademeister",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+600000 Scherben pro Klick",
    buyed: false,
    id: 20,
  },
  {
    image: gartenzwerg_soldat,
    costs: 75000000,
    anzahl: 1500000,
    possession: 0,
    title: "Soldat",
    type: UPGRADE_TYPES.KLICK,
    tooltipDescription: "+1500000 Scherben pro Klick",
    buyed: false,
    id: 21,
  },
];

export default upgradeList;
